OnlineStore/Store.App/Controllers/CartController.cs
using Microsoft.AspNet.Identity;
using Store.Data;
using Store.Models;
using Store.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Store.App.Controllers
{
    using System.Data.Entity;

    [Authorize]
    public class CartController : BaseController
    {
        public CartController(Context data) : base(data)
        {
        }

        // GET: Cart
        public ActionResult Index()
        {
            var cart = this.GetCartOfCurrentUser();

            if (cart.Products.Count == 0)
            {
                return this.View("EmptyCart");
            }

            return this.View(cart);
        }

        public ActionResult AddToCart(int id)
        {
            Product product = this.Data.Products.Find(id);
            if (product == null)
            {
                return this.HttpNotFound();
            }

            var cart = this.GetCartOfCurrentUser();
            var cartProduct = cart.Products.FirstOrDefault(cp => cp.ProductId == id);

            if (cartProduct == null)
            {
                cartProduct = new CartProduct
                {
                    ProductId = id,
                    Cart = cart,
                    Quantity = 0
                };
            }

            cartProduct.Quantity++;

            cart.Products.Add(cartProduct);
            this.Data.SaveChanges();

            return this.RedirectToAction("Index");
        }

        public ActionResult RemoveFromCart(int id)
        {
            var cart = this.GetCartOfCurrentUser();
            var cartProduct = cart.Products.FirstOrDefault(cp => cp.ProductId == id);
            cart.Products.Remove(cartProduct);
            this.Data.SaveChanges();

            return this.RedirectToAction("Index");
        }

        public ActionResult FinalizePurchase(int cartId)
        {
            var cart = this.GetCartOfCurrentUser();
            if (cart.Products.Count == 0)
            {
                return this.RedirectToAction("Index");
            }

            foreach (var product in cart.Products)
            {
                var soldProduct = this.Data.Products.FirstOrDefault(p => p.Id == product.ProductId);
                if (soldProduct == null)
                {
                    cart.Products.Remove(product);
                    return this.RedirectToAction("Index");
                }
                
                if (soldProduct.Quantity - product.Quantity < 0)
                {
                    product.Quantity = soldProduct.Quantity;
                    return this.RedirectToAction("Index");
                }
            }

          
            var order = new Order() { UserId = this.UserProfile.Id };
            foreach (var product in cart.Products)
            {
                var soldProduct = this.Data.Products.FirstOrDefault(p => p.Id == product.ProductId);
                soldProduct.Quantity -= product.Quantity;
                var orderedProduct = new OrderProduct()
                {
                    Product = soldProduct,
                    Quantity = product.Quantity,
                    Order = order
                };

                order.Products.Add(orderedProduct);
            }

            cart.Products.Clear();
            this.Data.SaveChanges();

            return this.View(order);
        }

        private Cart GetCartOfCurrentUser()
        {
            var cart = this.Data.Carts.Include(c => c.Products).FirstOrDefault(c => c.User.Id == this.UserProfile.Id);
            if (cart == null)
            {
                cart = new Cart();
                this.UserProfile.Cart = cart;
            }

            return cart;
        }
    }
}

OnlineStore/Store.App/Controllers/ShopController.cs
namespace Store.App.Controllers
{
    using System.Linq;
    using Services;
    using ViewModels;
    using System.Web.Mvc;
    using Store.Models;

    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index(int page = 1, int count = 6, string category = null)
        {
            var managerProducts = new ProductService();
            var managerCategories = new CategoryService();

            var products = managerProducts.Get();
            var categories = managerCategories.Get();
            if (category !=null)
            {
                products = products.Where(p => p.Category.Name == category).ToList();
            }

            int productsCount = products.Count;
            products = products.Skip((page - 1) * count)
                .Take(count)
                .ToList();
            
            this.ViewBag.TotalPages = (productsCount + count - 1) / count;
            this.ViewBag.CurrentPage = page;
            this.ViewBag.CurrentCategory = category;

            var model = new ShopViewModel
            {
                Categories = categories,
                Products = products
            };

            return this.View(model);
        }

        public ActionResult Details(int id)
        {
            var managerProducts = new ProductService();
            var product = managerProducts.Get(id);

            return this.View(product);
        }
    }
}

OnlineStore/Store.App/Views/Shop/Details.cshtml
@model Store.Models.Product

@{
    ViewBag.Title = "Details";
}

<div class="row single-product">
    <div class="col-md-3">
        <img src='~/Content/Images/Products/@Model.FullPicturePath' />
    </div>
    <div class="col-md-9">
        <span class="home-product-name">@Model.Name</span>
        <span class="product-description">@Model.Description</span>
        <span class="home-product-price">$@Model.Price</span>
        @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { Model.Id }, new { calss = "addtocart-btn" })
    </div>
</div>

OnlineStore/Store.App/Views/Shop/Index.cshtml
@model Store.ViewModels.ShopViewModel

<div class="row">
    <div class="col-sm-3">
        <h3 class="text-center">Categories</h3>
        <section class="buttons">
            <a href="/Shop/Index/" class="draw meet">
                <span>All</span>
            </a>
            @foreach (var category in Model.Categories)
            {
                <a href="/Shop/Index/?category=@category.Name" class="draw meet">
                    <span>@category.Name</span>
                </a>
            }
        </section>
    </div>

    <div class="col-md-9">
        <div class="row">
            @Html.DisplayFor(m => m.Products)
        </div>
    </div>
    
    @if (ViewBag.TotalPages > 1)
    {
        <div class="col-md-9 col-md-offset-3">
            <ul class="pagination">
                @for (int page = 1; page <= ViewBag.TotalPages; page++)
                {
                    string listItemClass = string.Empty;
                    if (page == ViewBag.CurrentPage)
                    {
                        listItemClass = "active";
                    }

                    <li class="@listItemClass">@Html.ActionLink(page.ToString(), "Index", "Shop", routeValues: new {page = page, count = 6, category = ViewBag.CurrentCategory}, htmlAttributes: null)</li>
                }
            </ul>
        </div>
    }
</div>